# Default initial positions for kinova's ros2_control fake system

initial_positions:
  j2s6s200_joint_1: 0
  j2s6s200_joint_2: 0
  j2s6s200_joint_3: 0
  j2s6s200_joint_4: 0
  j2s6s200_joint_5: 0
  j2s6s200_joint_6: 0
  j2s6s200_joint_finger_1: 0
  j2s6s200_joint_finger_2: 0