# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator_controller

  manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j2s6s200_joint_1
      - j2s6s200_joint_2
      - j2s6s200_joint_3
      - j2s6s200_joint_4
      - j2s6s200_joint_5
      - j2s6s200_joint_6
    action_ns: follow_joint_trajectory
    default: true