# Default initial positions for franka_panda's ros2_control fake system

initial_positions:
  panda_finger_joint1: 0
  panda_finger_joint2: 0
  panda_joint1: 0
  panda_joint2: 0
  panda_joint3: 0
  panda_joint4: -1.3188
  panda_joint5: 0.3682
  panda_joint6: 1.7529
  panda_joint7: 0.9444